package finance;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Riwayat_transaksi extends javax.swing.JFrame {

    public Riwayat_transaksi() {
        initComponents();
        showRiwayat_transaksi();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        tf_cari = new javax.swing.JTextField();
        btn_cari = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        btn_refresh = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Riwayat Transaksi");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(197, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(192, 192, 192))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(102, 51, 0));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Table Transaksi");

        tf_cari.setBackground(new java.awt.Color(255, 255, 255));
        tf_cari.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tf_cari.setForeground(new java.awt.Color(0, 0, 0));

        btn_cari.setBackground(new java.awt.Color(0, 51, 51));
        btn_cari.setForeground(new java.awt.Color(204, 204, 204));
        btn_cari.setText("Cari");
        btn_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cariActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Tanggal", "Nama Kasir", "Shift", "Metode Pembayaran", "Total Pembayaran"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setBackground(new java.awt.Color(153, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Home");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btn_refresh.setBackground(new java.awt.Color(51, 153, 0));
        btn_refresh.setForeground(new java.awt.Color(255, 255, 255));
        btn_refresh.setText("Refresh");
        btn_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_refreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tf_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_cari))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8)
                    .addComponent(tf_cari)
                    .addComponent(btn_cari, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void showRiwayat_transaksi() {

        try {
            java.sql.Connection conn = datacaffegui02.Koneksi.koneksiDb();
            String sql = "SELECT t.id_transaksi, t.waktu_transaksi, sh.nama, sh.shift,t.metode_bayar, t.total_bayar "
                    + "FROM transaksi t INNER JOIN shift sh ON t.id_shift = sh.id_shift";
            java.sql.Statement st = conn.createStatement();
            java.sql.ResultSet rs = st.executeQuery(sql);

            DefaultTableModel model = new DefaultTableModel(
                    new String[]{"ID Transaksi", "Waktu", "Nama Kasir", "Shift","Metode Pembayaran","Total Bayar"}, 0);

            while (rs.next()) {
                String id = rs.getString("id_transaksi");
                String tgl = rs.getString("waktu_transaksi");
                String nama = rs.getString("nama");
                String shift = rs.getString("shift");
                String mtd_byr = rs.getString("metode_bayar");
                String total = rs.getString("total_bayar");

                model.addRow(new Object[]{id, tgl, nama, shift,mtd_byr,total});
            }
            jTable1.setModel(model);

            st.close();
            rs.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal mengambil data: " + e.getMessage());

        }
    }

    public void showTransaksi_detail(String id_transaksi) {
        try {
            java.sql.Connection conn = datacaffegui02.Koneksi.koneksiDb();
            String sql = "SELECT td.id_detail, td.id_transaksi, m.nama_menu, um.ukuran, td.jumlah, td.total_harga " +
                    "FROM transaksi_detail td " +
                    "INNER JOIN menu m ON td.id_menu = m.id_menu " +
                    "INNER JOIN ukuran_menu um ON td.id_ukuran = um.id_ukuran " +
                    "WHERE td.id_transaksi = ?";

            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, id_transaksi);
            java.sql.ResultSet rs = pst.executeQuery();

            boolean dataDitemukan = false;

            DefaultTableModel model = new DefaultTableModel(
                    new String[]{"ID_Detail", "ID_transaksi", "nama_menu", "ukuran", "jumlah", "total_harga"}, 0);

            while (rs.next()) {

                dataDitemukan = true;

                String id_detail = rs.getString("id_detail");
                String idTrx = rs.getString("id_transaksi");
                String menu = rs.getString("nama_menu");
                String ukuran = rs.getString("ukuran");
                int jumlah = rs.getInt("jumlah");
                int total = rs.getInt("total_harga");

                model.addRow(new Object[]{id_detail, idTrx, menu, ukuran, jumlah, total});
            }
            jTable1.setModel(model);

            if (!dataDitemukan) {
                JOptionPane.showMessageDialog(null, "ID Transaksi \"" + id_transaksi + "\" tidak ditemukan.");
                System.err.println( "ID Transaksi \"" + id_transaksi + "\" tidak ditemukan.");
            }

            pst.close();
            rs.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal mengambil detail transaksi: " + e.getMessage());
            e.printStackTrace();
        }
    }
    
    private void btn_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cariActionPerformed
        // TODO add your handling code here:
        String id_transaksi = tf_cari.getText().trim().toUpperCase();
        if (!id_transaksi.isEmpty()) {
            showTransaksi_detail(id_transaksi);
        } else {
            JOptionPane.showMessageDialog(null, "Masukkan ID Transaksi terlebih dahulu MasPur!");
        }
    }//GEN-LAST:event_btn_cariActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        MenuFinance f = new MenuFinance();
        f.pack();
        f.setLocationRelativeTo(null);
        f.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_refreshActionPerformed
        // TODO add your handling code here:
        showRiwayat_transaksi();
        tf_cari.setText("");
    }//GEN-LAST:event_btn_refreshActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cari;
    private javax.swing.JButton btn_refresh;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField tf_cari;
    // End of variables declaration//GEN-END:variables
}
