package Barista;

import java.sql.Connection;
import javax.swing.JOptionPane;
import java.sql.ResultSet;

import java.sql.PreparedStatement;

public class CashForm extends javax.swing.JFrame {

    private String barista;
    private String id_transaksiOn;

    public CashForm(int subTotal, int ppn, int totalSemua, String barista, String id_transaksiOn) {
        super("Cash Form");

        this.barista = barista;
        this.id_transaksiOn = id_transaksiOn;

        initComponents();
        
        tf_ppn.setText(String.format("Rp%,d",ppn));
        rf_subTotal.setText(String.format("Rp%,d", subTotal));
        tf_totalBayar.setText(String.format("Rp%,d", totalSemua));
    }
    public String generateID_transaksi(Connection conn){
        String prefix = "TRX";
        String sql = "SELECT * FROM transaksi ORDER BY id_transaksi DESC LIMIT 1";
        String id_baru = "";
        
        try{
            conn = datacaffegui02.Koneksi.koneksiDb();
            PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            
            if(rs.next()){
                String id_lama = rs.getString("id_transaksi");
                
                String angka = id_lama.substring(3);
                int nomor = Integer.parseInt(angka);
                id_baru = String.format("%s%03d",prefix,nomor+1);
            }else{
                id_baru = prefix + "001";
            }
        }catch(Exception e){
            e.printStackTrace();
        }
        return id_baru;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        rf_subTotal = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tf_ppn = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tf_totalBayar = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tf_uangDibayar = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tf_kembalian = new javax.swing.JTextField();
        btn_bayar = new javax.swing.JButton();
        btn_keluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("CASH FORM");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addContainerGap(207, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel1)))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel3.setBackground(new java.awt.Color(51, 0, 0));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Sub Total");

        rf_subTotal.setEditable(false);
        rf_subTotal.setBackground(new java.awt.Color(255, 255, 255));
        rf_subTotal.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        rf_subTotal.setForeground(new java.awt.Color(0, 0, 0));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("PPN 12%");

        tf_ppn.setEditable(false);
        tf_ppn.setBackground(new java.awt.Color(255, 255, 255));
        tf_ppn.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tf_ppn.setForeground(new java.awt.Color(0, 0, 0));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Total Bayar");

        tf_totalBayar.setEditable(false);
        tf_totalBayar.setBackground(new java.awt.Color(255, 255, 255));
        tf_totalBayar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tf_totalBayar.setForeground(new java.awt.Color(0, 0, 0));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Uang Dibayar");

        tf_uangDibayar.setBackground(new java.awt.Color(255, 255, 255));
        tf_uangDibayar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tf_uangDibayar.setForeground(new java.awt.Color(0, 0, 0));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Kembalian");

        tf_kembalian.setEditable(false);
        tf_kembalian.setBackground(new java.awt.Color(255, 255, 255));
        tf_kembalian.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tf_kembalian.setForeground(new java.awt.Color(0, 0, 0));

        btn_bayar.setBackground(new java.awt.Color(255, 102, 0));
        btn_bayar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_bayar.setForeground(new java.awt.Color(255, 255, 255));
        btn_bayar.setText("Bayar");
        btn_bayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bayarActionPerformed(evt);
            }
        });

        btn_keluar.setBackground(new java.awt.Color(0, 255, 51));
        btn_keluar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_keluar.setForeground(new java.awt.Color(0, 0, 0));
        btn_keluar.setText("Keluar");
        btn_keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_keluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addComponent(btn_bayar, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_keluar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_kembalian, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_uangDibayar, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_totalBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_ppn, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rf_subTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(rf_subTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tf_ppn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tf_totalBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tf_uangDibayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tf_kembalian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_keluar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_bayar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_bayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bayarActionPerformed
        // TODO add your handling code here:
        try{ 
            String cash = "Cash";
            String subTotalStr = rf_subTotal.getText().replace("Rp","").replace(".","").replace(",","").trim();
            String ppnStr = tf_ppn.getText().replace("Rp","").replace(".","").replace(",","").trim();
            
            int subTotal = Integer.parseInt(subTotalStr);
            int ppn = Integer.parseInt(ppnStr);
            
            String totalStr = tf_totalBayar.getText().replace("Rp","").replace(".","").replace(",","").trim();
            String dibayarStr = tf_uangDibayar.getText().replace(".","").replace(",","").trim();
            
            int totalSemua = Integer.parseInt(totalStr);
            int bayar = Integer.parseInt(dibayarStr);   
            
            if(bayar < totalSemua){
                JOptionPane.showMessageDialog(this,"Uangnya kurang Maspur!");
                return;
            }
            
            int kembalian = bayar - totalSemua;
            tf_kembalian.setText("Rp" + String.format("%,d", kembalian));
            JOptionPane.showMessageDialog(this, "Pembayaran berhasil dengan CASH.");
            
            try{
                Connection conn = datacaffegui02.Koneksi.koneksiDb();
                String sql_transaksi 
                        = "UPDATE transaksi SET metode_bayar = ?,sub_total = ?, ppn = ?"
                        + ",total_bayar = ?, waktu_transaksi = ?, id_shift = ? WHERE id_transaksi = ?";
                PreparedStatement pst_transaksi = conn.prepareStatement(sql_transaksi);
                
                // get ID_shift
                String id_shift = "";
                String sqlID_shift = "SELECT id_shift FROM shift WHERE nama = ?";
                PreparedStatement pstID_shift = conn.prepareStatement(sqlID_shift);
                pstID_shift.setString(1, barista);
                
                ResultSet rsID_shift = pstID_shift.executeQuery();
                if(rsID_shift.next()){
                    id_shift = rsID_shift.getString("id_shift");
                }
                
                pstID_shift.close();
                rsID_shift.close();
      
                pst_transaksi.setString(1, cash);
                pst_transaksi.setInt(2, subTotal);
                pst_transaksi.setInt(3, ppn);
                pst_transaksi.setInt(4, totalSemua);
                pst_transaksi.setDate(5, new java.sql.Date(System.currentTimeMillis()));
                pst_transaksi.setString(6, id_shift);
                pst_transaksi.setString(7, id_transaksiOn);
                
                pst_transaksi.executeUpdate();                
                pst_transaksi.close();
                
                String sql_bayarcash = "INSERT INTO pembayaran_cash(id_transaksi,uang_dibayar,kembalian) VALUES(?,?,?)";
                PreparedStatement pst_bayarCash = conn.prepareStatement(sql_bayarcash);
                
                pst_bayarCash.setString(1, id_transaksiOn);
                pst_bayarCash.setInt(2, bayar);
                pst_bayarCash.setInt(3, kembalian);
                
                pst_bayarCash.executeUpdate();
                pst_bayarCash.close();
                
               
        
                
            }catch(Exception e){
                e.printStackTrace();
            }
            
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Input tidak valid!");
        }     
        
         id_transaksiOn = null; 
         this.dispose();
    }//GEN-LAST:event_btn_bayarActionPerformed

    private void btn_keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_keluarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btn_keluarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_bayar;
    private javax.swing.JButton btn_keluar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField rf_subTotal;
    private javax.swing.JTextField tf_kembalian;
    private javax.swing.JTextField tf_ppn;
    private javax.swing.JTextField tf_totalBayar;
    private javax.swing.JTextField tf_uangDibayar;
    // End of variables declaration//GEN-END:variables
}
