/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Barista;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

/**
 *
 * @author yan
 */
public class ValidasiKasir extends javax.swing.JDialog {

    /**
     * Creates new form ValidasiKasir
     */
    public ValidasiKasir(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
     public void setFormKasir(String nama, String shift){
        tf_namaKasir.setText(nama);
        cbb_shift.setSelectedItem(shift);
    }
    
    public String generateID_shift(Connection conn){
        
        String prefix = "SHF";
        String sql = "SELECT * FROM shift ORDER BY id_shift DESC LIMIT 1";
        String id_baru = "";
        
        try{
            conn = datacaffegui02.Koneksi.koneksiDb();
            PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            
            if(rs.next()){
                
                String id_lama = rs.getString("id_shift");
                String angka = id_lama.substring(3);
                int nomor = Integer.parseInt(angka);
                
                id_baru = String.format("%s%03d",prefix, nomor + 1);
            }else{
                id_baru = prefix + "001";
            }  
        }catch(Exception e){
            e.printStackTrace();
        }
         
        return id_baru;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tf_namaKasir = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cbb_shift = new javax.swing.JComboBox<>();
        btn_acc = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 0, 0));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("FORM BARISTA");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/person_apron_50dp.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addContainerGap(331, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(33, 33, 33))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(102, 51, 0));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("NAMA KASIR");

        tf_namaKasir.setBackground(new java.awt.Color(255, 255, 255));
        tf_namaKasir.setForeground(new java.awt.Color(0, 0, 0));
        tf_namaKasir.setText("Masukkan nama Anda...");
        tf_namaKasir.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tf_namaKasirFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf_namaKasirFocusLost(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("JADWAL SHITF");

        cbb_shift.setBackground(new java.awt.Color(255, 255, 255));
        cbb_shift.setForeground(new java.awt.Color(0, 0, 0));
        cbb_shift.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pagi - Sore", "Sore - Malam" }));

        btn_acc.setBackground(new java.awt.Color(0, 153, 0));
        btn_acc.setForeground(new java.awt.Color(255, 255, 255));
        btn_acc.setText("ACC");
        btn_acc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_accActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(cbb_shift, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3)
                    .addComponent(tf_namaKasir)
                    .addComponent(btn_acc, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_namaKasir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbb_shift, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_acc, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_namaKasirFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_namaKasirFocusGained
        // TODO add your handling code here:
        if(tf_namaKasir.getText().equals("Masukkan nama Anda...")){
            tf_namaKasir.setText("");
        }
    }//GEN-LAST:event_tf_namaKasirFocusGained

    private void tf_namaKasirFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_namaKasirFocusLost
        // TODO add your handling code here:
        if(tf_namaKasir.getText().equals("")){
            tf_namaKasir.setText("Masukkan nama Anda...");
        }
    }//GEN-LAST:event_tf_namaKasirFocusLost

    private void btn_accActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_accActionPerformed
        // TODO add your handling code here:
        String namaKasir = tf_namaKasir.getText();
        String shift = cbb_shift.getSelectedItem().toString();
        String role = "barista";

        LocalDate today = LocalDate.now();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd-MM-yyyy");
        String formattedDate = today.format(formatter);

        if(namaKasir.isBlank()|| namaKasir.equals("Masukkan nama Anda...") || shift.isBlank()){
            JOptionPane.showMessageDialog(this, "Nama Kasir atau shift ga boleh kosong MasPur!"
                ,"INGPO MasPur!", JOptionPane.ERROR_MESSAGE);
        }else{
            try{

                // shift akun
                Connection conn = datacaffegui02.Koneksi.koneksiDb();
                String sql_shift
                = "INSERT INTO shift (id_shift,nama,shift,id_user,tgl)"
                + "VALUES(?,?,?,?,?)";
                PreparedStatement pst_shift = conn.prepareStatement(sql_shift);

                String id_shift = generateID_shift(conn);

                // get ID_user
                String id_user = "";
                String sqlID_user = "SELECT id_user from user WHERE role = ?";
                PreparedStatement pstID_user = conn.prepareStatement(sqlID_user);
                pstID_user.setString(1, role);

                ResultSet rsID_user = pstID_user.executeQuery();

                if(rsID_user.next()){
                    id_user = rsID_user.getString("id_user");
                }

                // INSERT ke table shift
                pst_shift.setString(1, id_shift);
                pst_shift.setString(2, namaKasir);
                pst_shift.setString(3, shift);
                pst_shift.setString(4, id_user);
                pst_shift.setDate(5, java.sql.Date.valueOf(today));

                pst_shift.executeUpdate();
                pst_shift.close();

                // SHIFT-USER
                String sqlShift_User = "INSERT INTO shift_user(id_user,id_shift) VALUES(?,?)";
                PreparedStatement pst_Shift_user = conn.prepareStatement(sqlShift_User);
                pst_Shift_user.setString(1, id_user);
                pst_Shift_user.setString(2, id_shift);

                pst_Shift_user.executeUpdate();
                pst_Shift_user.close();

                rsID_user.close();
                pstID_user.close();

            }catch(Exception e){
                e.printStackTrace();
            }
            MenuKasir mk = new MenuKasir();
            mk.pack();
            mk.setFormBarista(namaKasir, shift,formattedDate);
            mk.setLocationRelativeTo(null);
            mk.setVisible(true);
            this.dispose();

        }
    }//GEN-LAST:event_btn_accActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_acc;
    private javax.swing.JComboBox<String> cbb_shift;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField tf_namaKasir;
    // End of variables declaration//GEN-END:variables
}
